development:
  adapter: postgresql
  host: localhost
  database: <%= ENV['POSTGRES_DBNAME'] || "dynamicdb_development" %>
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: dynamicdb_test
  pool: 5
  timeout: 5000
