development:
  adapter: postgresql
  host: localhost
  database: <%= ENV['POSTGRES_DBNAME'] || "dynamicdb_development" %>
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: dynamicdb_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: <%= dbname = ENV['POSTGRES_DBNAME']; puts "DBNAME = #{dbname.inspect}"; dbname %>
  username: <%= username = ENV['POSTGRES_USERNAME']; puts "USERNAME = #{username.inspect}"; username %>
  password: <%= password = ENV['POSTGRES_PASSWORD']; puts "PASSWORD = #{password.inspect}"; password %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  timeout: 5000
