development:
  adapter: postgresql
  host: localhost
  database: <%= ENV['POSTGRES_DBNAME'] || "dynamicdb_development" %>
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: dynamicdb_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: <%= ENV['POSTGRES_DBNAME'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  timeout: 5000
